//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrmCustomer {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrmCustomer.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Bankbalance! ähnelt.
        /// </summary>
        internal static string ExceptionBankBalForb {
            get {
                return ResourceManager.GetString("ExceptionBankBalForb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer number invalid! ähnelt.
        /// </summary>
        internal static string ExceptionCustNumForb {
            get {
                return ResourceManager.GetString("ExceptionCustNumForb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Day in LastChange! ähnelt.
        /// </summary>
        internal static string ExceptionDayForb {
            get {
                return ResourceManager.GetString("ExceptionDayForb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database should be empty before importing customers! ähnelt.
        /// </summary>
        internal static string ExceptionDBNotEmpty {
            get {
                return ResourceManager.GetString("ExceptionDBNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first element of your first name should be a capital letter! ähnelt.
        /// </summary>
        internal static string ExceptionFirstNameCapitalLetter {
            get {
                return ResourceManager.GetString("ExceptionFirstNameCapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your first name should have at least one letter! ähnelt.
        /// </summary>
        internal static string ExceptionFirstNameEmpty {
            get {
                return ResourceManager.GetString("ExceptionFirstNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your first name should only include letters! ähnelt.
        /// </summary>
        internal static string ExceptionFirstNameLetters {
            get {
                return ResourceManager.GetString("ExceptionFirstNameLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Hour in LastChange! ähnelt.
        /// </summary>
        internal static string ExceptionHourForb {
            get {
                return ResourceManager.GetString("ExceptionHourForb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your chosen Filename is invalid. Please check it again. ähnelt.
        /// </summary>
        internal static string ExceptionInvalFileName {
            get {
                return ResourceManager.GetString("ExceptionInvalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File could not be read because of invalid password! ähnelt.
        /// </summary>
        internal static string ExceptionInvalPassw {
            get {
                return ResourceManager.GetString("ExceptionInvalPassw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first element of your last name should be a capital letter! ähnelt.
        /// </summary>
        internal static string ExceptionLastNameCapitalLetter {
            get {
                return ResourceManager.GetString("ExceptionLastNameCapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your last name should have at least one letter! ähnelt.
        /// </summary>
        internal static string ExceptionLastNameEmpty {
            get {
                return ResourceManager.GetString("ExceptionLastNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your last name should only include letters! ähnelt.
        /// </summary>
        internal static string ExceptionLastNameLetters {
            get {
                return ResourceManager.GetString("ExceptionLastNameLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only letters are allowed as domain! ähnelt.
        /// </summary>
        internal static string ExceptionMailDomain {
            get {
                return ResourceManager.GetString("ExceptionMailDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This mail still exists! Please choose another one. ähnelt.
        /// </summary>
        internal static string ExceptionMailExists {
            get {
                return ResourceManager.GetString("ExceptionMailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too few symbols before your @ symbol. At least one Symbol is required! ähnelt.
        /// </summary>
        internal static string ExceptionMailFewSymbBeforeAt {
            get {
                return ResourceManager.GetString("ExceptionMailFewSymbBeforeAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail contains forbidden symbols! ähnelt.
        /// </summary>
        internal static string ExceptionMailForbSymb {
            get {
                return ResourceManager.GetString("ExceptionMailForbSymb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too few symbols after your @ symbol! ähnelt.
        /// </summary>
        internal static string ExceptionMailMuchSymbAfterAt {
            get {
                return ResourceManager.GetString("ExceptionMailMuchSymbAfterAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail contains too much @-symbols! ähnelt.
        /// </summary>
        internal static string ExceptionMailTooManyAt {
            get {
                return ResourceManager.GetString("ExceptionMailTooManyAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your mail is too short or does not exist an @-Symbol! ähnelt.
        /// </summary>
        internal static string ExceptionMailToShort {
            get {
                return ResourceManager.GetString("ExceptionMailToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Minute in LastChange! ähnelt.
        /// </summary>
        internal static string ExceptionMinuteForb {
            get {
                return ResourceManager.GetString("ExceptionMinuteForb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Month in LastChange! ähnelt.
        /// </summary>
        internal static string ExceptionMonthForb {
            get {
                return ResourceManager.GetString("ExceptionMonthForb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This SortValue doesn&apos;t exist! ähnelt.
        /// </summary>
        internal static string ExceptionQuickSortForb {
            get {
                return ResourceManager.GetString("ExceptionQuickSortForb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Second in LastChange! ähnelt.
        /// </summary>
        internal static string ExceptionSecondForb {
            get {
                return ResourceManager.GetString("ExceptionSecondForb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail contains too less . after your @! ähnelt.
        /// </summary>
        internal static string ExceptionToLessPointsAfterAt {
            get {
                return ResourceManager.GetString("ExceptionToLessPointsAfterAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User not found! ähnelt.
        /// </summary>
        internal static string ExceptionUserNotFound {
            get {
                return ResourceManager.GetString("ExceptionUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password should have at least 1 and max. 16 characters! ähnelt.
        /// </summary>
        internal static string ExceptionWrongPassw {
            get {
                return ResourceManager.GetString("ExceptionWrongPassw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Year in LastChange! ähnelt.
        /// </summary>
        internal static string ExceptionYearForb {
            get {
                return ResourceManager.GetString("ExceptionYearForb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail contains . on forbidden positions. These are not allowed at the start/end and before/after @! ähnelt.
        /// </summary>
        internal static string ExpcetionMailFrobPoints {
            get {
                return ResourceManager.GetString("ExpcetionMailFrobPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too few/much symbols at the ending. These must be at least 2 and max. 4! ähnelt.
        /// </summary>
        internal static string ExpcetionMailNumSymb {
            get {
                return ResourceManager.GetString("ExpcetionMailNumSymb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail contains too much . after your @! ähnelt.
        /// </summary>
        internal static string ExpcetionMailToMuchPointsAfterAt {
            get {
                return ResourceManager.GetString("ExpcetionMailToMuchPointsAfterAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Surname ähnelt.
        /// </summary>
        internal static string Frm1DgvLabelHeader1 {
            get {
                return ResourceManager.GetString("Frm1DgvLabelHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forename ähnelt.
        /// </summary>
        internal static string Frm1DgvLabelHeader2 {
            get {
                return ResourceManager.GetString("Frm1DgvLabelHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Change ähnelt.
        /// </summary>
        internal static string Frm1DgvLabelHeader4 {
            get {
                return ResourceManager.GetString("Frm1DgvLabelHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank Balance ähnelt.
        /// </summary>
        internal static string Frm1DgvLabelHeader5 {
            get {
                return ResourceManager.GetString("Frm1DgvLabelHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string Frm1Label1u4 {
            get {
                return ResourceManager.GetString("Frm1Label1u4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename ähnelt.
        /// </summary>
        internal static string Frm1Label2u3 {
            get {
                return ResourceManager.GetString("Frm1Label2u3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string Frm1LabelBtnEdit {
            get {
                return ResourceManager.GetString("Frm1LabelBtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ähnelt.
        /// </summary>
        internal static string Frm1LabelBtnLoad {
            get {
                return ResourceManager.GetString("Frm1LabelBtnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment ähnelt.
        /// </summary>
        internal static string Frm1LabelBtnPay {
            get {
                return ResourceManager.GetString("Frm1LabelBtnPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Frm1LabelBtnSave {
            get {
                return ResourceManager.GetString("Frm1LabelBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        internal static string Frm1LabelBtnSearch {
            get {
                return ResourceManager.GetString("Frm1LabelBtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Database ähnelt.
        /// </summary>
        internal static string Frm1LabelGroupBox2 {
            get {
                return ResourceManager.GetString("Frm1LabelGroupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search by: ähnelt.
        /// </summary>
        internal static string Frm1LabelGroupBox3 {
            get {
                return ResourceManager.GetString("Frm1LabelGroupBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Database ähnelt.
        /// </summary>
        internal static string Frm1LabelGroupBox5 {
            get {
                return ResourceManager.GetString("Frm1LabelGroupBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Customer ähnelt.
        /// </summary>
        internal static string Frm1LableBtnAdd {
            get {
                return ResourceManager.GetString("Frm1LableBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer Data ähnelt.
        /// </summary>
        internal static string Frm1Text {
            get {
                return ResourceManager.GetString("Frm1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forename ähnelt.
        /// </summary>
        internal static string FrmAddLabelGroupBox1 {
            get {
                return ResourceManager.GetString("FrmAddLabelGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Surname ähnelt.
        /// </summary>
        internal static string FrmAddLabelGroupBox2 {
            get {
                return ResourceManager.GetString("FrmAddLabelGroupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Customer ähnelt.
        /// </summary>
        internal static string FrmAddText {
            get {
                return ResourceManager.GetString("FrmAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer-Number ähnelt.
        /// </summary>
        internal static string FrmEditLabelGroupBox1 {
            get {
                return ResourceManager.GetString("FrmEditLabelGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New-Surname ähnelt.
        /// </summary>
        internal static string FrmEditLabelGroupBox2 {
            get {
                return ResourceManager.GetString("FrmEditLabelGroupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New-E-Mail ähnelt.
        /// </summary>
        internal static string FrmEditLabelGroupBox3 {
            get {
                return ResourceManager.GetString("FrmEditLabelGroupBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type in a number! ähnelt.
        /// </summary>
        internal static string FrmEditNumberReq {
            get {
                return ResourceManager.GetString("FrmEditNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Customer ähnelt.
        /// </summary>
        internal static string FrmEditText {
            get {
                return ResourceManager.GetString("FrmEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer-Number ähnelt.
        /// </summary>
        internal static string FrmPayLabelGroupBox1 {
            get {
                return ResourceManager.GetString("FrmPayLabelGroupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment ähnelt.
        /// </summary>
        internal static string FrmPayLabelGroupBox2 {
            get {
                return ResourceManager.GetString("FrmPayLabelGroupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inpayment ähnelt.
        /// </summary>
        internal static string FrmPayLabelRdb1 {
            get {
                return ResourceManager.GetString("FrmPayLabelRdb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outpayment ähnelt.
        /// </summary>
        internal static string FrmPayLabelRdb2 {
            get {
                return ResourceManager.GetString("FrmPayLabelRdb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This Customer-Number is not available! ähnelt.
        /// </summary>
        internal static string FrmPayNoCustomer {
            get {
                return ResourceManager.GetString("FrmPayNoCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment ähnelt.
        /// </summary>
        internal static string FrmPayText {
            get {
                return ResourceManager.GetString("FrmPayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paasword ähnelt.
        /// </summary>
        internal static string FrmWelcomeLabel1 {
            get {
                return ResourceManager.GetString("FrmWelcomeLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename ähnelt.
        /// </summary>
        internal static string FrmWelcomeLabel2 {
            get {
                return ResourceManager.GetString("FrmWelcomeLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Database ähnelt.
        /// </summary>
        internal static string FrmWelcomeLabelGroupbox {
            get {
                return ResourceManager.GetString("FrmWelcomeLabelGroupbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string FrmWelcomeLabelGroupbox3 {
            get {
                return ResourceManager.GetString("FrmWelcomeLabelGroupbox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string FrmWelcomeLabelRdbEnglish {
            get {
                return ResourceManager.GetString("FrmWelcomeLabelRdbEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        internal static string FrmWelcomeLabelRdbGerman {
            get {
                return ResourceManager.GetString("FrmWelcomeLabelRdbGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Database ähnelt.
        /// </summary>
        internal static string FrmWelcomeLabelRdbLoad {
            get {
                return ResourceManager.GetString("FrmWelcomeLabelRdbLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Database ähnelt.
        /// </summary>
        internal static string FrmWelcomeLabelRdbNew {
            get {
                return ResourceManager.GetString("FrmWelcomeLabelRdbNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome ähnelt.
        /// </summary>
        internal static string FrmWelcomeText {
            get {
                return ResourceManager.GetString("FrmWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully stored! ähnelt.
        /// </summary>
        internal static string MassageBoxSave {
            get {
                return ResourceManager.GetString("MassageBoxSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, not found! ähnelt.
        /// </summary>
        internal static string MassageBoxSearch {
            get {
                return ResourceManager.GetString("MassageBoxSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database successfully loaded! ähnelt.
        /// </summary>
        internal static string MassegeBoxLoad {
            get {
                return ResourceManager.GetString("MassegeBoxLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are able to search by: Forename, Surname and Customer Number ähnelt.
        /// </summary>
        internal static string TootipTextSearch {
            get {
                return ResourceManager.GetString("TootipTextSearch", resourceCulture);
            }
        }
    }
}
